# Generated by Django 5.0.7 on 2024-07-13 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasmApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionplan',
            name='rmbudget',
        ),
        migrations.AddField(
            model_name='actionplan',
            name='budgetext',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rasmApp.budgetext'),
        ),
    ]
