# Generated by Django 5.0.7 on 2024-07-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasmApp', '0002_remove_actionplan_rmbudget_actionplan_budgetext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmbudget',
            name='segment',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
