# Generated by Django 5.0.7 on 2024-07-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasmApp', '0004_alter_actionplan_forthemonth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetext',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='rmbudget',
            name='consultant',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
