# Generated by Django 5.0.7 on 2024-07-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasmApp', '0005_alter_budgetext_options_alter_rmbudget_consultant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmbudget',
            name='maintenancetypes',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
