# Generated by Django 5.0.7 on 2024-07-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasmApp', '0006_alter_rmbudget_maintenancetypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmbudget',
            name='contractorN',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
