# Generated by Django 5.0.7 on 2024-07-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasmApp', '0007_alter_rmbudget_contractorn'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPerRoadType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bdistrict', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('bfinancer', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('bzone', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('bproject', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('bprojectname', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('broadsegment', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('byear', models.DateField()),
                ('Asphalt', models.FloatField(blank=True, default=None, null=True)),
                ('Gravel', models.FloatField(blank=True, default=None, null=True)),
                ('remark', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'budgetperroadtypeTb',
                'ordering': ['bdistrict'],
            },
        ),
        migrations.CreateModel(
            name='ERABudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bdistrict', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('bfinancer', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('bzone', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('bproject', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('bprojectname', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('broadsegment', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('byear', models.DateField()),
                ('budgetamount', models.FloatField(blank=True, default=None, null=True)),
                ('remark', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'erabudgetTb',
                'ordering': ['bdistrict'],
            },
        ),
    ]
