# Generated by Django 5.0.7 on 2024-07-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasmApp', '0008_budgetperroadtype_erabudget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erabudget',
            name='budgetamount',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
