# Generated by Django 5.0.7 on 2024-07-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasmApp', '0010_remove_erabudget_budgetamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='erabudget',
            name='budgetamount',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
