# Generated by Django 5.0.7 on 2024-07-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasmApp', '0011_erabudget_budgetamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erabudget',
            name='budgetamount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True),
        ),
    ]
