# Generated by Django 5.0.7 on 2024-07-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasmApp', '0013_alter_erabudget_budgetamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='erabudget',
            name='budgetAmt',
            field=models.FloatField(null=True),
        ),
    ]
