# Generated by Django 5.0.7 on 2024-07-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasmApp', '0014_erabudget_budgetamt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rmbudget',
            name='regions',
        ),
        migrations.AddField(
            model_name='rmbudget',
            name='regionalgovernment',
            field=models.ManyToManyField(to='rasmApp.regionalgovernment'),
        ),
    ]
