# Generated by Django 5.0.7 on 2024-07-27 05:16

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rasmApp', '0015_remove_rmbudget_regions_rmbudget_regionalgovernment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rmbudget',
            name='regionalgovernment',
        ),
        migrations.AddField(
            model_name='rmbudget',
            name='regions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('አማራ', 'አማራ'), ('አፋር', 'አፋር'), ('ቤኒሻንጉል-ጉሙዝ', 'ቤኒሻንጉል-ጉሙዝ'), ('ድሬዳዋ', 'ድሬዳዋ'), ('ጋምቤላ', 'ጋምቤላ'), ('ሀረሪ', 'ሀረሪ'), ('ኦሮሚያ', 'ኦሮሚያ'), ('ደቡብ ኢትዮጵያ', 'ደቡብ ኢትዮጵያ'), ('ሶማሊ', 'ሶማሊ'), ('ደቡብ ምዕራብ ኢትዮጵያ', 'ደቡብ ምዕራብ ኢትዮጵያ'), ('ትግራይ', 'ትግራይ'), ('ሲዳማ', 'ሲዳማ')], default=None, max_length=75, null=True),
        ),
    ]
