# Generated by Django 5.0.7 on 2024-07-29 02:36

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasmApp', '0016_remove_rmbudget_regionalgovernment_rmbudget_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='erabudget',
            name='basphalt',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='erabudget',
            name='bconsultant',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='erabudget',
            name='bcontractor',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='erabudget',
            name='bcontractorname',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='erabudget',
            name='bgravel',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='erabudget',
            name='bregion',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='erabudget',
            name='bworktype',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='erabudget',
            name='bdistrict',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='erabudget',
            name='bprojectname',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='erabudget',
            name='broadsegment',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='erabudget',
            name='bzone',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rmbudget',
            name='regions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('አማራ', 'አማራ'), ('አፋር', 'አፋር'), ('ቤኒሻንጉል-ጉሙዝ', 'ቤኒሻንጉል-ጉሙዝ'), ('ድሬዳዋ', 'ድሬዳዋ'), ('ጋምቤላ', 'ጋምቤላ'), ('ሀረሪ', 'ሀረሪ'), ('ኦሮሚያ', 'ኦሮሚያ'), ('ደቡብ ኢትዮጵያ', 'ደቡብ ኢትዮጵያ'), ('ሶማሊ', 'ሶማሊ'), ('ደቡብ ምዕራብ ኢትዮጵያ', 'ደቡብ ምዕራብ ኢትዮጵያ'), ('ትግራይ', 'ትግራይ'), ('ሲዳማ', 'ሲዳማ'), ('ማዕከላዊ ኢትዮጵያ', 'ማዕከላዊ ኢትዮጵያ'), ('በኔትወርክ ውስጥ በሚገኙ ክልሎች', 'በኔትወርክ ውስጥ በሚገኙ ክልሎች'), ('በኔትወርኩ ስር በሚገኙ  መንገዶች', 'በኔትወርኩ ስር በሚገኙ  መንገዶች'), ('ድሬደዋና የተለያዩ ክልሎች', 'ድሬደዋና የተለያዩ ክልሎች'), ('በሁሉም', 'በሁሉም')], default=None, max_length=152, null=True),
        ),
        migrations.AlterField(
            model_name='road',
            name='regions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('አማራ', 'አማራ'), ('አፋር', 'አፋር'), ('ቤኒሻንጉል-ጉሙዝ', 'ቤኒሻንጉል-ጉሙዝ'), ('ድሬዳዋ', 'ድሬዳዋ'), ('ጋምቤላ', 'ጋምቤላ'), ('ሀረሪ', 'ሀረሪ'), ('ኦሮሚያ', 'ኦሮሚያ'), ('ደቡብ ኢትዮጵያ', 'ደቡብ ኢትዮጵያ'), ('ሶማሊ', 'ሶማሊ'), ('ደቡብ ምዕራብ ኢትዮጵያ', 'ደቡብ ምዕራብ ኢትዮጵያ'), ('ትግራይ', 'ትግራይ'), ('ሲዳማ', 'ሲዳማ'), ('ማዕከላዊ ኢትዮጵያ', 'ማዕከላዊ ኢትዮጵያ'), ('በኔትወርክ ውስጥ በሚገኙ ክልሎች', 'በኔትወርክ ውስጥ በሚገኙ ክልሎች'), ('በኔትወርኩ ስር በሚገኙ  መንገዶች', 'በኔትወርኩ ስር በሚገኙ  መንገዶች'), ('ድሬደዋና የተለያዩ ክልሎች', 'ድሬደዋና የተለያዩ ክልሎች'), ('በሁሉም', 'በሁሉም')], default=None, max_length=152, null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='regions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('አማራ', 'አማራ'), ('አፋር', 'አፋር'), ('ቤኒሻንጉል-ጉሙዝ', 'ቤኒሻንጉል-ጉሙዝ'), ('ድሬዳዋ', 'ድሬዳዋ'), ('ጋምቤላ', 'ጋምቤላ'), ('ሀረሪ', 'ሀረሪ'), ('ኦሮሚያ', 'ኦሮሚያ'), ('ደቡብ ኢትዮጵያ', 'ደቡብ ኢትዮጵያ'), ('ሶማሊ', 'ሶማሊ'), ('ደቡብ ምዕራብ ኢትዮጵያ', 'ደቡብ ምዕራብ ኢትዮጵያ'), ('ትግራይ', 'ትግራይ'), ('ሲዳማ', 'ሲዳማ'), ('ማዕከላዊ ኢትዮጵያ', 'ማዕከላዊ ኢትዮጵያ'), ('በኔትወርክ ውስጥ በሚገኙ ክልሎች', 'በኔትወርክ ውስጥ በሚገኙ ክልሎች'), ('በኔትወርኩ ስር በሚገኙ  መንገዶች', 'በኔትወርኩ ስር በሚገኙ  መንገዶች'), ('ድሬደዋና የተለያዩ ክልሎች', 'ድሬደዋና የተለያዩ ክልሎች'), ('በሁሉም', 'በሁሉም')], default=None, max_length=152, null=True),
        ),
    ]
