# Generated by Django 5.0.7 on 2024-07-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasmApp', '0017_erabudget_basphalt_erabudget_bconsultant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='erabudget',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='erabudget',
            name='byear',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
