# Generated by Django 5.0.7 on 2024-07-29 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasmApp', '0020_bactionplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetedactionplan',
            name='erabudget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rasmApp.erabudget'),
        ),
    ]
