# Generated by Django 5.0.7 on 2024-07-29 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasmApp', '0021_alter_budgetedactionplan_erabudget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bactionplan',
            name='erabudget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rasmApp.erabudget'),
        ),
    ]
