# Generated by Django 5.0.7 on 2024-07-29 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasmApp', '0022_alter_bactionplan_erabudget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetedactionplan',
            name='erabudget',
        ),
        migrations.AddField(
            model_name='budgetedactionplan',
            name='anbudget',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rasmApp.erabudget'),
        ),
        migrations.DeleteModel(
            name='BActionPlan',
        ),
    ]
