# Generated by Django 5.0.7 on 2024-08-13 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasmApp', '0030_budgetedap_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erabudget',
            name='bdistrict',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rasmApp.district'),
        ),
    ]
