# Generated by Django 5.0.7 on 2024-08-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasmApp', '0034_alter_erabudget_bworktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetedap',
            name='financialacomp',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='budgetedap',
            name='physicalacomp',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='budgetedap',
            name='remark1',
            field=models.CharField(blank=True, choices=[('በጦርነቱ/በፀጥታ ችግር ምክንያት', 'በጦርነቱ/በፀጥታ ችግር ምክንያት'), ('በኮንትራት የሚተዳደሩ ፕሮጀክቶች በመቋረጣቸው ምክንያት', 'በኮንትራት የሚተዳደሩ ፕሮጀክቶች በመቋረጣቸው ምክንያት'), ('በግዢ ሂደት ላይ ያሉ ፕሮጀክቶች', 'በግዢ ሂደት ላይ ያሉ ፕሮጀክቶች'), ('በግብአት እጥረት ምክንያት', 'በግብአት እጥረት ምክንያት'), ('በመንገድ ወሰን ማስከበር ምክንያት', 'በመንገድ ወሰን ማስከበር ምክንያት'), ('የተለያየ (Others)', 'የተለያየ (Others)')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='budgetedap',
            name='remark2',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
