# Generated by Django 5.0.7 on 2024-08-17 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rasmApp', '0035_budgetedap_financialacomp_budgetedap_physicalacomp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetedap',
            name='bapmonth',
        ),
        migrations.RemoveField(
            model_name='budgetedap',
            name='remark',
        ),
    ]
