# Generated by Django 5.0.7 on 2024-08-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasmApp', '0036_remove_budgetedap_bapmonth_remove_budgetedap_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomplishment',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
