# Generated by Django 5.0.7 on 2024-08-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasmApp', '0038_budgetedap_bapmonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomplishment',
            name='duetocontracttermination',
            field=models.CharField(blank=True, default='', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='accomplishment',
            name='other',
            field=models.CharField(blank=True, default='', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='accomplishment',
            name='resourceshortages',
            field=models.CharField(blank=True, default='', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='accomplishment',
            name='rightofwayissues',
            field=models.CharField(blank=True, default='', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='accomplishment',
            name='securityproblem',
            field=models.CharField(blank=True, default='', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='accomplishment',
            name='underprocurementprocess',
            field=models.CharField(blank=True, default='', max_length=240, null=True),
        ),
    ]
