# Generated by Django 5.0.7 on 2024-08-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasmApp', '0039_accomplishment_duetocontracttermination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomplishment',
            name='actionInBr',
            field=models.FloatField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='accomplishment',
            name='actionInKm',
            field=models.FloatField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='accomplishment',
            name='bremark2',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
