# Generated by Django 5.0.7 on 2024-08-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasmApp', '0040_alter_accomplishment_actioninbr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomplishment',
            name='bapmonth',
            field=models.CharField(blank=True, choices=[('--', '--'), ('Km', 'Km'), ('%', '%'), ('pcs', 'pcs')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accomplishment',
            name='unit',
            field=models.CharField(blank=True, choices=[('መስከረም', 'መስከረም'), ('ጥቅምት', 'ጥቅምት'), ('ህዳር', 'ህዳር'), ('ታህሳስ', 'ታህሳስ'), ('ጥር', 'ጥር'), ('የካቲት', 'የካቲት'), ('መጋቢት', 'መጋቢት'), ('ሚያዚያ', 'ሚያዚያ'), ('ግንቦት', 'ግንቦት'), ('ሰኔ', 'ሰኔ'), ('ሐምሌ', 'ሐምሌ'), ('ነሐሴ', 'ነሐሴ')], default='', max_length=10, null=True),
        ),
    ]
