# Generated by Django 5.0.7 on 2024-08-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasmApp', '0042_alter_accomplishment_bapmonth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomplishment',
            name='unit',
            field=models.CharField(blank=True, choices=[('Km', 'Km'), ('%', '%'), ('pcs', 'pcs')], default='', max_length=10, null=True),
        ),
    ]
