# Generated by Django 5.0.7 on 2024-10-19 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasmApp', '0044_alter_accomplishment_bapmonth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RMAactivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activitycode', models.CharField(max_length=3)),
                ('activity', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ActivityTb',
            },
        ),
        migrations.RemoveField(
            model_name='roadconditionsurvey',
            name='solution',
        ),
        migrations.AddField(
            model_name='roadconditionsurvey',
            name='qty',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='roadconditionsurvey',
            name='activity',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rasmApp.rmaactivity'),
        ),
    ]
