# Generated by Django 5.0.7 on 2024-10-19 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rasmApp', '0047_alter_roadconditionsurvey_problem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadconditionsurvey',
            name='roadSide',
        ),
    ]
