# Generated by Django 5.0.7 on 2024-10-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasmApp', '0048_remove_roadconditionsurvey_roadside'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadconditionsurvey',
            name='problem',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
