# Generated by Django 5.0.7 on 2024-11-06 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rasmApp', '0048_remove_roadconditionsurvey_roadside'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetedap',
            options={},
        ),
    ]
