# Generated by Django 5.0.7 on 2024-11-06 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rasmApp', '0050_alter_budgetedap_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetedap',
            options={'ordering': ['erabudget_id']},
        ),
    ]
