# Generated by Django 5.0.7 on 2024-11-09 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasmApp', '0054_alter_budgetedap_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadconditionsurvey',
            name='area',
        ),
        migrations.RemoveField(
            model_name='roadconditionsurvey',
            name='district',
        ),
        migrations.RemoveField(
            model_name='roadconditionsurvey',
            name='inspector',
        ),
        migrations.RemoveField(
            model_name='roadconditionsurvey',
            name='kmCount',
        ),
        migrations.RemoveField(
            model_name='roadconditionsurvey',
            name='range',
        ),
        migrations.RemoveField(
            model_name='roadconditionsurvey',
            name='segmentNo',
        ),
        migrations.RemoveField(
            model_name='roadconditionsurvey',
            name='startKm',
        ),
        migrations.RemoveField(
            model_name='roadconditionsurvey',
            name='surveyDate',
        ),
        migrations.AddField(
            model_name='roadconditionsurvey',
            name='actvty',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='roadconditionsurvey',
            name='extent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='roadconditionsurvey',
            name='qty',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='roadconditionsurvey',
            name='severity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='RoadSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roadname', models.CharField(max_length=100)),
                ('asphaltlength', models.FloatField(blank=True, null=True)),
                ('gravellength', models.FloatField(blank=True, null=True)),
                ('totall', models.FloatField(editable=False)),
                ('rfc_id', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('remark', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('modifiedon', models.DateTimeField(auto_now=True)),
                ('designstd', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rasmApp.designstandard')),
                ('district', models.ForeignKey(db_column='districtname', on_delete=django.db.models.deletion.CASCADE, to='rasmApp.district')),
                ('rfcclass', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rasmApp.rfcclass')),
                ('sectionname', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rasmApp.section')),
                ('surfacetype', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rasmApp.roadsurfacetype')),
            ],
            options={
                'db_table': 'RoadSegmentTb',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RoadSegmentExt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspector', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('fromlen', models.IntegerField()),
                ('tolen', models.IntegerField()),
                ('roadsegment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='rasmApp.roadsegment')),
            ],
            options={
                'db_table': 'RoadSegmentExtTb',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='roadconditionsurvey',
            name='roadsegext',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rasmApp.roadsegmentext'),
        ),
    ]
