# Generated by Django 5.0.7 on 2024-11-09 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rasmApp', '0055_remove_roadconditionsurvey_area_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RMAactivity',
            new_name='Activity',
        ),
    ]
