# Generated by Django 5.0.7 on 2024-11-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasmApp', '0056_rename_rmaactivity_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='unit',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='urate',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activitycode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
