# Generated by Django 5.0.7 on 2024-11-10 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rasmApp', '0057_activity_unit_activity_urate_alter_activity_activity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='roadconditionsurvey',
            options={'ordering': ['id']},
        ),
    ]
