# Generated by Django 5.0.7 on 2024-11-10 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rasmApp', '0058_alter_activity_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rfcclass',
            options={'ordering': ['id']},
        ),
    ]
