# Generated by Django 5.0.7 on 2024-11-11 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rasmApp', '0049_alter_roadconditionsurvey_problem'),
        ('rasmApp', '0060_alter_rmproblem_options'),
    ]

    operations = [
    ]
