# Generated by Django 5.0.7 on 2024-11-16 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasmApp', '0061_merge_20241111_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadconditionsurvey',
            name='problem',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rasmApp.rmproblem'),
        ),
    ]
